# Render Blueprint for Vite + React application
services:
  - type: web
    name: contact-gain-vcf-generator
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    env: node
    envVars:
      - key: NODE_ENV
        value: production
    # If you need environment variables for Supabase:
    # - key: VITE_SUPABASE_URL
    #   value: your-supabase-url
    # - key: VITE_SUPABASE_ANON_KEY
    #   value: your-supabase-key
    plan: free
    staticSite: false
    healthCheckPath: /